task 0

diff --git a/0x00-python-hello_world/0-run b/0x00-python-hello_world/0-run
--- a/0x00-python-hello_world/0-run
+++ b/0x00-python-hello_world/0-run
@@ -1,3 +1,16 @@
 #!/bin/bash
-python3 "$PYFILE"
 
+# Check if the PYFILE environment variable is set
+if [ -z "$PYFILE" ]; then
+	echo "Error: PYFILE environment variable not set. Please export the filename of the Python script."
+	exit 1
+fi
+
+# Check if the file specified in the PYFILE variable exists
+if [ ! -f "$PYFILE" ]; then
+	echo "Error: The file '$PYFILE' does not exist."
+	exit 1
+fi
+
+# Execute the Python script
+python3 "$PYFILE"
